[package]
name = "phantom-circuits"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
phantom-lattice = { path = "../phantom-lattice" }
phantom-schemes = { path = "../phantom-schemes" }
phantom-utils = { path = "../phantom-utils" }
thiserror.workspace = true

[dev-dependencies]
phantom-ring = { path = "../phantom-ring" }
rand_chacha.workspace = true
